server {
    listen 80;
    server_name _;
    
    root /usr/share/nginx/html;
    
    # Разрешаем доступ к certbot challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }
    
    # Все остальное - статика сайта
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}

